#!/bin/bash



COUNTER=1
DADO1=0
DADO2=0
DADO3=0
PLAYERS=1
PLAYER1=0
TURN=1
DUQUES=0
CHECK=0
ESCALERA=0
BRINCO=0
ARRAY=("Numbers:")
TOTAL1=0

echo "-----------------------"
echo "--Welcome to TopoLoco--"
echo "-----------------------"
echo ""
echo "GAME RULES"
echo "----------"
echo "1. This game is played with 3 dice"
echo "2. Each player takes 1 turn to throw all 3 dice"
echo "3. For each turn, the player will sum the points" 
echo "for each play"
echo "4. The game ends when a player gets the Topoloco"
echo "or if the 4th turn for each player ends"
echo "------------------------------------------------"
echo ""
echo "SCORE DEFENITIONS"
echo "-----------------"
echo "Toploco: Same number of each dice"
echo "Escalera: Three consecutive numbers.  All numbers are added to the score."
echo "Duque: Adds two numbers that are equal to the score."
echo "Brinco: Two pairs or two odd. All numbers are added to the score."
echo "Adjudicar: If the hand does not exist in a play, you will only add one number to the score"
echo "------------------------------------------------------------------------------------------"
while [ $COUNTER -le 2 ]; do
	echo Player $PLAYERS is throwing dice...
	echo ""
	while [ $TURN -le 4 ];	do
		echo Turn $TURN
		let DADO1=$(( ( RANDOM % 6 ) +1 ))
		let DADO2=$(( ( RANDOM % 6 ) +1 ))
		let DADO3=$(( ( RANDOM % 6 ) +1 ))
		echo Numbers of the 3 dice: $DADO1 $DADO2 $DADO3

		#Checking if the dices have the same value
		if [[ "$DADO1|$DADO2|$DADO3" = "$DADO1|$DADO1|$DADO1" ]]; then
			echo "Player $PLAYERS have won!"
			let CHECK=1
		#	let TURN=4
		#	let COUNTER=2
			exit
		fi

		#Ordenando los dados
		nos=($DADO1 $DADO2 $DADO3)
		#echo ${nos[@]} | awk 'BEGIN{RS= " ";} {print $1}' | sort 
		if [ ${nos[0]} -ge ${nos[1]} ]; then
			temp=${nos[0]}
			nos[0]=${nos[1]}
			nos[1]=$temp
		fi
		if [ ${nos[1]} -ge ${nos[2]} ]; then
			temp=${nos[1]}
			nos[1]=${nos[2]}
			nos[2]=$temp
		fi
		if [ ${nos[0]} -ge ${nos[1]} ]; then
			temp=${nos[0]}
			nos[0]=${nos[1]}
			nos[1]=$temp
		fi

		#INSERTING MENU!!!!!!
		OPTIONS="DUQUE BRINCO ESCALERA ADJUDICAR FORFEIT"
		select opt in $OPTIONS; do
			#9th option: Escalera
			if [ "$opt" = "ESCALERA" ]; then
				#Check if it is empty...
				if [ $ESCALERA -eq 0 ]; then 
					#Adding Escalera
					if [[ "${nos[0]}|${nos[1]}|${nos[2]}" = "1|2|3" ]]; then
						let ESCALERA+=nos[0]+nos[1]+nos[2]
						echo "ESCALERA: " $ESCALERA
						break
						#echo SUCCESS
					elif [[ "${nos[0]}|${nos[1]}|${nos[2]}" = "2|3|4" ]]; then
						let ESCALERA+=nos[0]+nos[1]+nos[2]
						echo "ESCALERA: " $ESCALERA
						break
						#echo SUCCES"ESCALERA: " 
					elif [[ "${nos[0]}|${nos[1]}|${nos[2]}" = "3|4|5" ]]; then
						let ESCALERA+=nos[0]+nos[1]+nos[2]
						echo "ESCALERA: " $ESCALERA
						break
						#echo SUCCESS
					elif [[ "${nos[0]}|${nos[1]}|${nos[2]}" = "4|5|6" ]]; then
						let ESCALERA+=nos[0]+nos[1]+nos[2]
						echo "ESCALERA: " $ESCALERA
						break
						#echo SUCCESS
					fi 
						echo No hubo escalera. Selecione otra opcion
				else
						echo No está vacío.  Escoja otra opción
				fi
			
			#8th Option: Brinco
			elif [ "$opt" = "BRINCO" ]; then
				#Check if it empty...
				if [ $BRINCO -eq 0 ]; then
					#Adding Brinco
					#BRINCO
					if [ "${nos[1]}" == $((nos[0]+2)) ] || [ "${nos[2]}" == $((nos[1]+2)) ]; then
						let BRINCO+=nos[0]+nos[1]+nos[2] 
						echo "BRINCO: " $BRINCO
						break
					fi
					echo No hubo brinco.  Selecione otra opcion.
				else
					echo No está vacío.  Escoja otra opción.
				fi
			#7th Option: DUQUE
			elif [ "$opt" = "DUQUE" ]; then
				if [ $DUQUES -eq 0 ]; then
					#Compara si dos dados son iguales en cada if
					if [ $DADO1 = $DADO3 ]; then
						let DUQUES+=$DADO1+$DADO3
						echo "DUQUE: " $DUQUES
						break
					elif [ $DADO1 = $DADO2 ]; then
						let DUQUES+=$DADO1+$DADO2
						echo "DUQUE: " $DUQUES
						break
					elif [ $DADO2 = $DADO3 ]; then
						let DUQUES+=$DADO2+$DADO3
						echo "DUQUE: " $DUQUES
						break
					else
						echo No hubo duque.  Selecione otra opcion	
					fi
				else
					echo No está vacio.  Escoje otra opcion.  
				fi
			#Adjunte
			elif [ "$opt" = "ADJUDICAR" ]; then
				echo ""
				echo "Press 1 for Dice #1"
				echo "Press 2 for Dice #2"
				echo "Press 3 for Dice #3"
				echo "Press 4 to exit ADJUTE option"
				echo ""
				echo Choose one of the 3 dice: $DADO1 $DADO2 $DADO3
				OPTIONS1="$DADO1 $DADO2 $DADO3 SALIR"
				select opt1 in $OPTIONS1; do

				if [ "$opt1" = "$DADO1" ]; then
                	#Checking if element exist
                	if [[ "${ARRAY[*]} " == *" $DADO1 "* ]]; then
                  		echo No se puede adjudicar
                	else
                  		ARRAY=("${ARRAY[@]}" "$DADO1")
                  		echo ${ARRAY[@]}
                  		let CHECK=1
                  		break
                	fi

               	elif [ "$opt1" = "$DADO2" ]; then

                	if [[ "${ARRAY[*]} " == *" $DADO2 "* ]]; then
                  		echo No se puede adjudicar
                	else
                  		ARRAY=("${ARRAY[@]}" "$DADO2")
                  		echo ${ARRAY[@]}
                  		let CHECK=1
                  		break
                	fi

               	elif [ "$opt1" = "$DADO3" ]; then

                	if [[ "${ARRAY[*]} " == *" $DADO3 "* ]]; then
                  		echo No se puede adjudicar
                	else
                  		ARRAY=("${ARRAY[@]}" "$DADO3")
                  		echo ${ARRAY[@]}
                  		let CHECK=1
                  		break
                  		
                	fi
                elif [ "$opt1" = "SALIR" ]; then
                	break

               	else
                	echo Escoja una opción válida.

               fi
           done
           echo ""
           if [ "$CHECK" = 1 ]; then
           		let CHECK=0
           		break
           fi

           echo "1) DUQUE"
		   echo "2) BRINCO"
		   echo "3) ESCALERA"
		   echo "4) ADJUDICAR"
		   echo "5) FORFEIT"

           #END SECOND OPTION (ADJUDICAR)
           	elif [ "$opt" = "FORFEIT" ]; then
            	if [ "$PLAYERS" -eq 2 ]; then
            		echo "Player" $PLAYERS "has forfeit"
            		echo "Player 1 wins!"
            		exit
            	elif [ "$PLAYERS" -eq 1 ]; then
            		echo "Player 2 wins!" 
            		exit
       			fi	

			fi
		done
		#END FIRST OPTION 
	let TURN+=1
	echo ""
	done
	echo ""
	TEMP=("${ARRAY[@]}")
	unset TEMP[0]
	item=0

	for ((i=0; i <= ${#TEMP[@]}; i++)) do
		let item=$((TEMP[$i] + item))
	done

	TOTAL=0
	TOTAL=$((DUQUES + ESCALERA + BRINCO + item))
	echo Player $PLAYERS total points:  $TOTAL
	
	if [ $PLAYERS -eq 1 ]; then
		TOTAL1=$TOTAL
		PLAYER1=$PLAYERS
	fi

	let COUNTER=COUNTER+1
	let PLAYERS+=1
	
	let TEMP=0
	let item=0
	ARRAY=("Numbers:")
	
	ESCALERA=0
	BRINCO=0
	DUQUES=0
	TURN=1
	
	echo "---------------------------------"
	echo ""
done


#Winner.  If Second TOTAL is less than TOTAL1 (which is Player1), then Player1 WINZ


if [ "$TOTAL" -lt "$TOTAL1" ]; then
	echo "Player" $PLAYER1 "wins with a total of: " $TOTAL1
elif [ "$TOTAL" -eq "$TOTAL1" ]; then
	echo "It's a tie!"
else
	echo "Player 2 wins with a total of: " $TOTAL
fi


